/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_gstu_it_domain_IntegralSolver */

#ifndef _Included_by_gstu_it_domain_IntegralSolver
#define _Included_by_gstu_it_domain_IntegralSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_gstu_it_domain_IntegralSolver
 * Method:    solve
 * Signature: (Ljava/lang/String;[I)D
 */
JNIEXPORT jdouble JNICALL Java_by_gstu_it_domain_IntegralSolver_solve
  (JNIEnv *, jobject, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
